title: Kristoffer Naley Nornes
name: Kristoffer Naley Nornes
description: "Driftskoordinator & Styreleder"
url: "https://knornes.no" # Bytt ut med ditt domene
baseurl: ""

# Tema-innstillinger
# Slett alle linjer som starter med "theme:"
remote_theme: "mmistakes/minimal-mistakes"

# GitHub Pages innstillinger
url: "https://dittnavn.no" # Bruk ditt faktiske domene her
baseurl: ""

# Plugins som Minimal Mistakes krever
plugins:
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-include-cache

# Minimal Mistakes spesifikke innstillinger
minimal_mistakes_skin: "air"

# Personlig info (vises i margen)
author:
  name: "Kristoffer Naley Nornes"
  avatar: "/assets/images/profil.jpg" # Her kan du legge til bilde senere
  bio: "Driftskoordinator hos Tide Bane & Styreleder."
  location: "Bergen, Norge"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:kristoffer.n.nornes@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kristoffernornes"

# Innholdsstyring
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
